const KNOWN_DOMAINS: Record<string, string> = {
  "landsec": "landsec.com",
  "land securities": "landsec.com",
  "british land": "britishland.com",
  "grosvenor": "grosvenor.com",
  "grosvenor group": "grosvenor.com",
  "ls tottenham court road limited": "landsec.com",
  "ls tottenham court road": "landsec.com",
  "258 investments": "258inv.com",
  "aew": "aeweurope.com",
  "aberdeen standard": "abrdn.com",
  "abrdn": "abrdn.com",
  "alvarez & marsal": "alvarezandmarsal.com",
  "alvarez and marsal": "alvarezandmarsal.com",
  "angelo gordon": "angelogordon.com",
  "apex capital": "apexcapitaluk.com",
  "appley": "appley.net",
  "ardent": "theardentcompanies.com",
  "ares management": "aresmgmt.com",
  "ares management uk": "aresmgmt.com",
  "argent related": "relatedargent.co.uk",
  "arkea reim": "arkea-reim.com",
  "avignon": "avignoncapital.com",
  "avignon capital": "avignoncapital.com",
  "aviva": "avivainvestors.com",
  "aviva investors": "avivainvestors.com",
  "axa real estate": "axa-im.com",
  "axa im": "axa-im.com",
  "barings": "barings.com",
  "battersea power station": "bpsdc.co.uk",
  "battersea power station development": "bpsdc.co.uk",
  "beltane": "beltaneglobal.com",
  "beltane global": "beltaneglobal.com",
  "bloomberg": "bloomberg.net",
  "brockton": "brocktoneverlast.com",
  "brockton everlast": "brocktoneverlast.com",
  "brydell": "brydellpartners.com",
  "brydell partners": "brydellpartners.com",
  "savills": "savills.co.uk",
  "knight frank": "knightfrank.co.uk",
  "cbre": "cbre.com",
  "jll": "jll.com",
  "jones lang lasalle": "jll.com",
  "cushman & wakefield": "cushmanwakefield.com",
  "cushman and wakefield": "cushmanwakefield.com",
  "cushman wakefield": "cushmanwakefield.com",
  "cushwake": "cushmanwakefield.com",
  "colliers": "colliers.com",
  "colliers international": "colliers.com",
  "bnp paribas": "realestate.bnpparibas.com",
  "bnp paribas real estate": "realestate.bnpparibas.com",
  "capita": "capita.com",
  "derwent london": "derwentlondon.com",
  "derwent": "derwentlondon.com",
  "great portland estates": "gpe.co.uk",
  "gpe": "gpe.co.uk",
  "shaftesbury": "shaftesburycapital.com",
  "shaftesbury capital": "shaftesburycapital.com",
  "capco": "capitalandcounties.com",
  "capital & counties": "capitalandcounties.com",
  "hammerson": "hammerson.com",
  "segro": "segro.com",
  "workspace": "workspace.co.uk",
  "workspace group": "workspace.co.uk",
  "helical": "helical.co.uk",
  "stanhope": "stanhopeplc.com",
  "argent": "argentllp.co.uk",
  "lendlease": "lendlease.com",
  "brookfield": "brookfield.com",
  "related argent": "relatedargent.co.uk",
  "westfield": "westfield.com",
  "unibail": "urw.com",
  "unibail-rodamco": "urw.com",
  "cadogan": "cadogan.co.uk",
  "howard de walden": "hdwe.co.uk",
  "portman estate": "portmanestate.co.uk",
  "the portman estate": "portmanestate.co.uk",
  "the crown estate": "thecrownestate.co.uk",
  "crown estate": "thecrownestate.co.uk",
  "gerald eve": "geraldeve.com",
  "allsop": "allsop.co.uk",
  "carter jonas": "carterjonas.co.uk",
  "carterjonas": "carterjonas.co.uk",
  "strutt & parker": "struttandparker.com",
  "strutt and parker": "struttandparker.com",
  "avison young": "avisonyoung.com",
  "avisonyoung": "avisonyoung.com",
  "deloitte": "deloitte.com",
  "pwc": "pwc.com",
  "ey": "ey.com",
  "kpmg": "kpmg.com",
  "newmark": "nmrk.com",
  "levy real estate": "levyrealestate.co.uk",
  "levy": "levyrealestate.co.uk",
  "gcw": "gcw.co.uk",
  "fmx": "fmxurban.com",
  "fmx urban": "fmxurban.com",
  "fmx urban property advisers": "fmxurban.com",
  "davis coffer lyons": "dcl.co.uk",
  "dcl": "dcl.co.uk",
  "jackson criss": "jacksoncriss.co.uk",
  "rapleys": "rapleys.com",
  "fhp property consultants": "fhp.co.uk",
  "fhp": "fhp.co.uk",
  "time retail partners": "timeretailpartners.com",
  "metis real estate": "metisrealestate.com",
  "metis real estate advisors": "metisrealestate.com",
  "smith price": "smithprice.co.uk",
  "stephen kane": "stephenkane.co.uk",
  "stephen kane & co": "stephenkane.co.uk",
  "belcor": "belcor.co.uk",
  "orinsen": "orinsen.co.uk",
  "box property": "boxproperty.co.uk",
  "boxprop": "boxproperty.co.uk",
  "morgan martin": "morganmartin.co.uk",
  "lewis craig": "lewiscraig.com",
  "central retail": "centralretail.co.uk",
  "centralretail": "centralretail.co.uk",
  "hsa retail": "hsaretail.co.uk",
  "harvey spack field": "hsf.co.uk",
  "harvey spackfield": "hsf.co.uk",
  "bkl property consultants": "bklprop.co.uk",
  "bklprop": "bklprop.co.uk",
  "wsb property consultants": "wsbproperty.co.uk",
  "wsb property": "wsbproperty.co.uk",
  "wsbproperty": "wsbproperty.co.uk",
  "pudney shuttleworth": "pudneyshuttleworth.co.uk",
  "whitelaw baikie figes": "wbfsurveyors.co.uk",
  "shackleton": "shackletonproperty.co.uk",
  "johnstone property consultants": "johnstoneproperty.co.uk",
  "hynes illingworth": "hynesillingworth.co.uk",
  "eyco": "eyco.co.uk",
  "eyco llp": "eyco.co.uk",
  "medway & law": "medwayandlaw.co.uk",
  "medway and law": "medwayandlaw.co.uk",
  "howie property": "howieproperty.co.uk",
  "barker proudlove": "barkerproudlove.co.uk",
  "barkerproudlove": "barkerproudlove.co.uk",
  "brasier freeth": "brasierfreeth.com",
  "brasierfreeth": "brasierfreeth.com",
  "klm real estate": "klmre.com",
  "klm property": "klmre.com",
  "fleurets": "fleurets.com",
  "graham sibbald": "grahamsibbald.co.uk",
  "graham & sibbald": "grahamsibbald.co.uk",
  "etch": "etchgroup.co.uk",
  "etchgroup": "etchgroup.co.uk",
  "mason partners": "masonpartners.com",
  "dma": "dmaproperty.co.uk",
  "dmaproperty": "dmaproperty.co.uk",
  "restaurant property": "restaurantproperty.com",
  "lunson mitchenall": "lunsonmitchenall.co.uk",
  "ej hales": "ejhales.com",
  "e j hales": "ejhales.com",
  "ejhales": "ejhales.com",
  "mason owen": "masonowen.com",
  "street property consultants": "streetpropertyconsultants.co.uk",
  "arc retail": "arc-retail.co.uk",
  "arcretail": "arc-retail.co.uk",
  "mckinnon nelson": "mckinnonnelson.com",
  "strettons": "strettons.co.uk",
  "jenkins law": "jenkinslaw.co.uk",
  "nulty cader": "nultycader.com",
  "maykels": "maykels.com",
  "maykels chartered surveyors": "maykels.com",
  "francis & company": "francisandcompany.com",
  "francis and company": "francisandcompany.com",
  "francisandcompany": "francisandcompany.com",
  "one voice hospitality": "onevoicehospitality.com",
  "hicks baker": "hicksbaker.co.uk",
  "hicksbaker": "hicksbaker.co.uk",
  "aird estates": "airdestates.co.uk",
  "airdestates": "airdestates.co.uk",
  "may & company": "mayandcompany.co.uk",
  "may and company": "mayandcompany.co.uk",
  "emanuel oliver": "emanueloliver.com",
  "emanueloliver": "emanueloliver.com",
  "lyons thompson letts": "ltlproperty.com",
  "amt commercial": "amtcommercial.co.uk",
  "amtcommercial": "amtcommercial.co.uk",
  "fox lloyd jones": "foxlloydjones.com",
  "bruce gillingham pollard": "brucegillinghampollard.com",
  "brucegillinghampollard": "brucegillinghampollard.com",
  "bgp": "brucegillinghampollard.com",
  "dmr property": "dmrproperty.co.uk",
  "dmrproperty": "dmrproperty.co.uk",
  "as retail": "asretail.co.uk",
  "asretail": "asretail.co.uk",
  "@retail": "atretail.co.uk",
  "atretail": "atretail.co.uk",
  "ap retail": "apretail.co.uk",
  "dtr surveyors": "dtrsurveyors.co.uk",
  "dtrsurveyors": "dtrsurveyors.co.uk",
  "edgerley simpson howe": "eshp.co.uk",
  "edgerley simpson howe & partners": "eshp.co.uk",
  "eshp": "eshp.co.uk",
  "creative retail": "creativeretail.co.uk",
  "creativeretail": "creativeretail.co.uk",
  "cradick retail": "cradickretail.co.uk",
  "coffer corporate leisure": "coffergroup.co.uk",
  "cedar dean": "cedardean.com",
  "cedardean": "cedardean.com",
  "daniel watney": "danielwatney.co.uk",
  "danielwatney": "danielwatney.co.uk",
  "curson sowerby": "cspconsultants.co.uk",
  "csp curson sowerby": "cspconsultants.co.uk",
  "cspretail": "cspconsultants.co.uk",
  "cooke & arkwright": "cooke-arkwright.co.uk",
  "wright silverwood": "wrightsilverwood.co.uk",
  "wrightsilverwood": "wrightsilverwood.co.uk",
  "wright buchanan": "wrightbuchanan.co.uk",
  "wright property": "wrightproperty.co.uk",
  "wrightproperty": "wrightproperty.co.uk",
  "wright partners": "wrightandpartners.co.uk",
  "wrightandpartners": "wrightandpartners.co.uk",
  "victor harris": "victorharris.co.uk",
  "victor harris commercial": "victorharris.co.uk",
  "salloway property consultants": "salloway.com",
  "salloway": "salloway.com",
  "sanderson weatherall": "sw.co.uk",
  "sandersonweatherall": "sw.co.uk",
  "singer vielle": "singervielle.com",
  "singervielle": "singervielle.com",
  "spring property": "springproperty.co.uk",
  "springproperty": "springproperty.co.uk",
  "montagu evans": "montagu-evans.co.uk",
  "montaguevans": "montagu-evans.co.uk",
  "cluttons": "cluttons.com",
  "bidwells": "bidwells.co.uk",
  "lambert smith hampton": "lsh.co.uk",
  "lsh": "lsh.co.uk",
  "dtm legal": "dtmlegal.com",
  "vail williams": "vailwilliams.com",
  "vailwilliams": "vailwilliams.com",
  "glenny": "glenny.co.uk",
  "gva": "gva.co.uk",
  "stiles harold williams": "shw.co.uk",
  "shw": "shw.co.uk",
  "matthews & goodman": "matthews-goodman.co.uk",
  "matthews and goodman": "matthews-goodman.co.uk",
  "frost meadowcroft": "frostmeadowcroft.com",
  "mellersh & harding": "mellershandharding.co.uk",
  "mellersh and harding": "mellershandharding.co.uk",
  "hartnell taylor cook": "htc.uk.com",
  "hanover green": "hanovergreen.co.uk",
  "savills im": "savillsim.com",
  "christie & co": "christie.com",
  "christie co": "christie.com",
  "christie": "christie.com",
  "daltons business": "daltonsbusiness.com",
  "daltons": "daltonsbusiness.com",
  "acre capital": "acrecapital.co.uk",
  "acorn commercial": "acorngroup.co.uk",
  "agl": "agl.co.uk",
  "agllondon": "agl.co.uk",
  "hooper commercial": "hoopercommercial.co.uk",
  "hoopercommercialproperty": "hoopercommercial.co.uk",
  "griffin webster": "griffinwebster.com",
  "harper dennis hobbs": "hdh.uk.com",
  "hdh": "hdh.uk.com",
  "harris lamb": "harrislamb.com",
  "bastin commercial": "bastincommercial.co.uk",
  "bc retail": "bcretail.co.uk",
  "bennett real estate consultancy": "bennettrec.co.uk",
  "black stanniland": "blackstanniland.co.uk",
  "blackstanniland": "blackstanniland.co.uk",
  "brecker grossmith": "breckergrossmith.com",
  "brady chartered surveyors": "bradysurveyors.co.uk",
  "bradys": "bradysurveyors.co.uk",
  "boddy edwards": "boddyandedwards.co.uk",
  "boddyandedwards": "boddyandedwards.co.uk",
  "bury thorley": "burythorley.co.uk",
  "burns property consultants": "burnsproperty.co.uk",
  "carr priddle": "carrpriddle.co.uk",
  "carrpriddle": "carrpriddle.co.uk",
  "carter towler": "cartertowler.co.uk",
  "cartertowler": "cartertowler.co.uk",
  "cheetham mortimer": "cheethammortimer.co.uk",
  "colyer commercial": "colyercommercial.co.uk",
  "concept london": "conceptlondon.com",
  "crosthwaite commercial": "crosthwaitecommercial.co.uk",
  "dalkin co": "dalkin.co.uk",
  "dean gambles": "deangambles.co.uk",
  "dean gambles co": "deangambles.co.uk",
  "dibley property": "dibleyproperty.co.uk",
  "dibleyproperty": "dibleyproperty.co.uk",
  "downes property consulting": "downespropertyconsulting.co.uk",
  "downespropertyconsulting": "downespropertyconsulting.co.uk",
  "drake company": "drakeproperty.co.uk",
  "drakeproperty": "drakeproperty.co.uk",
  "durlings": "durlings.co.uk",
  "dutch & dutch": "dutchanddutch.com",
  "dutch dutch": "dutchanddutch.com",
  "dylan jones retail": "dylanjonesretail.co.uk",
  "ea commercial real estate": "eacre.co.uk",
  "eacre": "eacre.co.uk",
  "edit leisure": "editleisure.com",
  "egm property consultants": "egm.co.uk",
  "ewan mackay": "ewanmackay.co.uk",
  "exemplar": "exemplarhc.com",
  "exemplarhc": "exemplarhc.com",
  "farino cole": "farinocole.co.uk",
  "field sons": "fieldandsons.co.uk",
  "finch": "finchproperty.co.uk",
  "forge": "forgecommercial.co.uk",
  "forte commercial": "fortecommercial.co.uk",
  "fortecommercial": "fortecommercial.co.uk",
  "forty commercial": "fortygroup.co.uk",
  "forty group": "fortygroup.co.uk",
  "fortygroup": "fortygroup.co.uk",
  "four & co": "fourandco.com",
  "four co": "fourandco.com",
  "fourandco": "fourandco.com",
  "frazer kidd": "frazerkidd.co.uk",
  "fyfe mcdade": "fyfemcdade.com",
  "hitchcock wright": "hitchcockwright.co.uk",
  "hitchcock wright & partners": "hitchcockwright.co.uk",
  "hitchcock wright partners": "hitchcockwright.co.uk",
  "hordern ryan": "hordernryan.co.uk",
  "houston lawrence": "houstonlawrence.co.uk",
  "leaver charles granger": "lcgproperty.co.uk",
  "mcconnell property": "mcconnellproperty.co.uk",
  "raven green": "ravengreen.co.uk",
  "raven green & company": "ravengreen.co.uk",
  "tom powter": "tompowter.co.uk",
  "tom powter & co": "tompowter.co.uk",
  "wareing partners": "wareingpartners.co.uk",
  "whitby smith": "whitbysmith.co.uk",
  "williams property": "williamsproperty.co.uk",
  "wts commercial": "wtscommercial.co.uk",
  "wtscommercial": "wtscommercial.co.uk",
  "zeitlyn farrell": "zeitlynfarrell.co.uk",
  "zephyrus london": "zephyruz.com",
  "zephyruslondon": "zephyruz.com",
  "whitestone land": "whitestoneland.com",
  "wrather property": "wratherproperty.com",
  "xprop": "xprop.com",
  "cml property": "cmlproperty.co.uk",
  "walls property consultants": "wallsproperty.co.uk",
  "hickorys smokehouse": "hickorys.co.uk",
  "british heart foundation": "bhf.org.uk",
  "bhf": "bhf.org.uk",
  "frasers group": "frasers.group",
  "tenpin": "tenpin.co.uk",
  "one stop": "onestop.co.uk",
  "david lloyd": "davidlloyd.co.uk",
  "david lloyd leisure": "davidlloyd.co.uk",
  "deliveroo": "deliveroo.co.uk",
  "citibase": "citibase.co.uk",
  "citibase plc": "citibase.co.uk",
  "churchill retirement": "churchillretirement.co.uk",
  "amazon": "amazon.com",
  "google": "google.com",
  "apple": "apple.com",
  "microsoft": "microsoft.com",
  "meta": "meta.com",
  "facebook": "meta.com",
  "tesco": "tesco.com",
  "sainsbury": "sainsburys.co.uk",
  "sainsburys": "sainsburys.co.uk",
  "waitrose": "waitrose.com",
  "marks & spencer": "marksandspencer.com",
  "marks and spencer": "marksandspencer.com",
  "m&s": "marksandspencer.com",
  "h&m": "hm.com",
  "zara": "zara.com",
  "nike": "nike.com",
  "adidas": "adidas.com",
  "pret": "pret.com",
  "pret a manger": "pret.com",
  "costa": "costa.co.uk",
  "costa coffee": "costa.co.uk",
  "starbucks": "starbucks.com",
  "mcdonald's": "mcdonalds.com",
  "mcdonalds": "mcdonalds.com",
  "kfc": "kfc.com",
  "nando's": "nandos.co.uk",
  "nandos": "nandos.co.uk",
  "wagamama": "wagamama.com",
  "five guys": "fiveguys.com",
  "leon": "leon.co",
  "itsu": "itsu.com",
  "eat": "eat.co.uk",
  "greggs": "greggs.co.uk",
  "subway": "subway.com",
  "pizza express": "pizzaexpress.com",
  "pizza hut": "pizzahut.co.uk",
  "dominos": "dominos.co.uk",
  "domino's": "dominos.co.uk",
  "yo sushi": "yosushi.com",
  "the gym group": "thegymgroup.com",
  "puregym": "puregym.com",
  "virgin active": "virginactive.co.uk",
  "boots": "boots.com",
  "superdrug": "superdrug.com",
  "hsbc": "hsbc.com",
  "barclays": "barclays.co.uk",
  "lloyds": "lloydsbank.com",
  "natwest": "natwest.com",
  "nationwide": "nationwide.co.uk",
  "john lewis": "johnlewis.com",
  "harrods": "harrods.com",
  "selfridges": "selfridges.com",
  "harvey nichols": "harveynichols.com",
  "primark": "primark.com",
  "next": "next.co.uk",
  "asos": "asos.com",
  "gap": "gap.com",
  "uniqlo": "uniqlo.com",
  "lululemon": "lululemon.com",
  "jd sports": "jdsports.co.uk",
  "sports direct": "sportsdirect.com",
  "waterstones": "waterstones.com",
  "whsmith": "whsmith.co.uk",
  "wh smith": "whsmith.co.uk",
  "currys": "currys.co.uk",
  "argos": "argos.co.uk",
  "ikea": "ikea.com",
  "aldi": "aldi.co.uk",
  "lidl": "lidl.co.uk",
  "ocado": "ocado.com",
  "whole foods": "wholefoodsmarket.com",
  "soho house": "sohohouse.com",
  "wework": "wework.com",
  "regus": "regus.com",
  "iwg": "iwgplc.com",
  "burberry": "burberry.com",
  "gucci": "gucci.com",
  "louis vuitton": "louisvuitton.com",
  "lvmh": "lvmh.com",
  "chanel": "chanel.com",
  "prada": "prada.com",
  "hermes": "hermes.com",
  "tiffany": "tiffany.com",
  "cartier": "cartier.com",
  "rolex": "rolex.com",
  "swatch": "swatch.com",
  "pandora": "pandora.net",
  "ralph lauren": "ralphlauren.com",
  "tommy hilfiger": "tommy.com",
  "hugo boss": "hugoboss.com",
  "ted baker": "tedbaker.com",
  "reiss": "reiss.com",
  "cos": "cosstores.com",
  "mango": "mango.com",
  "massimo dutti": "massimodutti.com",
  "anthropologie": "anthropologie.com",
  "urban outfitters": "urbanoutfitters.com",
  "all saints": "allsaints.com",
  "river island": "riverisland.com",
  "topshop": "topshop.com",
  "the white company": "thewhitecompany.com",
  "jo malone": "jomalone.com",
  "lush": "lush.com",
  "holland & barrett": "hollandandbarrett.com",
  "nespresso": "nespresso.com",
  "joe & the juice": "joeandthejuice.com",
  "dishoom": "dishoom.com",
  "franco manca": "francomanca.co.uk",
  "byron": "byronhamburgers.com",
  "honest burgers": "honestburgers.co.uk",
  "gails": "gailsbread.co.uk",
  "gail's": "gailsbread.co.uk",
  "flat iron": "flatironsteak.co.uk",
  "hawksmoor": "thehawksmoor.com",
  "the ivy": "theivycollection.com",
  "bill's": "bills-website.co.uk",
  "bills": "bills-website.co.uk",
  "carluccio's": "carluccios.com",
  "carluccios": "carluccios.com",
  "wahaca": "wahaca.co.uk",
  "tortilla": "tortilla.co.uk",
  "chipotle": "chipotle.com",
  "shake shack": "shakeshack.com",
  "popeyes": "popeyes.com",
  "wingstop": "wingstop.com",
  "jd wetherspoon": "jdwetherspoon.com",
  "wetherspoon": "jdwetherspoon.com",
  "greene king": "greeneking.co.uk",
  "mitchells & butlers": "mbplc.com",
  "whitbread": "whitbread.co.uk",
  "premier inn": "premierinn.com",
  "travelodge": "travelodge.co.uk",
  "novotel": "novotel.com",
  "accor": "accor.com",
  "hilton": "hilton.com",
  "marriott": "marriott.com",
  "ihg": "ihg.com",
  "intercontinental": "ihg.com",
};

export function guessDomain(name: string | null | undefined): string | null {
  if (!name) return null;
  const lower = name.toLowerCase().trim();
  if (KNOWN_DOMAINS[lower]) return KNOWN_DOMAINS[lower];
  for (const [key, domain] of Object.entries(KNOWN_DOMAINS)) {
    if (lower.includes(key) || key.includes(lower)) return domain;
  }
  const slug = lower
    .replace(/\b(ltd|limited|plc|llp|inc|corp|group|holdings|uk|properties|property|estates|estate|real estate|international|partners|&|and|the)\b/gi, "")
    .replace(/[^a-z0-9]/g, "")
    .trim();
  if (slug.length >= 3) return `${slug}.com`;
  return null;
}

export function extractDomain(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const cleaned = raw.split(" - ")[0].trim();
  try {
    const url = cleaned.startsWith("http") ? cleaned : `https://${cleaned}`;
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    const stripped = cleaned.replace(/^https?:\/\//, "").replace(/^www\./, "").split("/")[0];
    return stripped || null;
  }
}

export function getCompanyLogoUrl(
  domain: string | null | undefined,
  name: string | null | undefined,
  size: number = 40
): string | null {
  const d = extractDomain(domain);
  if (d) return `https://www.google.com/s2/favicons?domain=${d}&sz=${Math.min(size * 2, 128)}`;
  const guessed = guessDomain(name);
  if (guessed) return `https://www.google.com/s2/favicons?domain=${guessed}&sz=${Math.min(size * 2, 128)}`;
  return null;
}
