export const CRM_OPTIONS = {
  companyType: [
    "Landlord",
    // ── Luxury ──
    "Tenant - Luxury",
    "Tenant - Luxury Accessories",
    "Tenant - Luxury Beauty",
    // ── Retail: Fashion ──
    "Tenant - Flagship Fashion",
    "Tenant - Fashion",
    "Tenant - Athleisure",
    "Tenant - Sportswear",
    "Tenant - Footwear",
    "Tenant - Accessories & Footwear",
    "Tenant - Jewellery & Watches",
    // ── Retail: Beauty ──
    "Tenant - Beauty",
    "Tenant - Skincare",
    "Tenant - Fragrance",
    // ── Retail: Home & Lifestyle ──
    "Tenant - Homewares",
    "Tenant - Lifestyle & Home",
    "Tenant - Gifts & Perfumes",
    // ── Retail: Other ──
    "Tenant - Department Store",
    "Tenant - Technology",
    "Tenant - Automotive",
    "Tenant - Telecoms",
    "Tenant - Grocery",
    "Tenant - Books & Stationery",
    "Tenant - Financial Services",
    "Tenant - Services",
    "Tenant - Retail",
    // ── Restaurants ──
    "Tenant - Fine Dining",
    "Tenant - Casual Dining",
    "Tenant - Restaurant",
    "Tenant - Quick Service",
    "Tenant - Café",
    "Tenant - Bar",
    "Tenant - Bakery",
    // ── Leisure ──
    "Tenant - Cinema",
    "Tenant - Experiential",
    "Tenant - Immersive Experience",
    "Tenant - Gaming",
    "Tenant - Family Entertainment",
    "Tenant - Leisure",
    // ── Health & Fitness ──
    "Tenant - Gym",
    "Tenant - Wellness",
    "Tenant - Yoga",
    "Agent",
  ],
  companyTypeColors: {
    "Landlord": "bg-amber-500",
    "Tenant - Luxury": "bg-yellow-600",
    "Tenant - Luxury Accessories": "bg-yellow-500",
    "Tenant - Luxury Beauty": "bg-yellow-400",
    "Tenant - Flagship Fashion": "bg-pink-700",
    "Tenant - Fashion": "bg-pink-600",
    "Tenant - Athleisure": "bg-pink-500",
    "Tenant - Sportswear": "bg-pink-500",
    "Tenant - Footwear": "bg-pink-400",
    "Tenant - Accessories & Footwear": "bg-pink-400",
    "Tenant - Jewellery & Watches": "bg-pink-300",
    "Tenant - Beauty": "bg-fuchsia-600",
    "Tenant - Skincare": "bg-fuchsia-500",
    "Tenant - Fragrance": "bg-fuchsia-400",
    "Tenant - Homewares": "bg-emerald-700",
    "Tenant - Lifestyle & Home": "bg-emerald-600",
    "Tenant - Gifts & Perfumes": "bg-emerald-500",
    "Tenant - Department Store": "bg-teal-700",
    "Tenant - Technology": "bg-sky-600",
    "Tenant - Automotive": "bg-sky-500",
    "Tenant - Telecoms": "bg-sky-400",
    "Tenant - Grocery": "bg-lime-600",
    "Tenant - Books & Stationery": "bg-amber-600",
    "Tenant - Financial Services": "bg-slate-600",
    "Tenant - Services": "bg-slate-500",
    "Tenant - Retail": "bg-teal-500",
    "Tenant - Fine Dining": "bg-rose-700",
    "Tenant - Casual Dining": "bg-rose-600",
    "Tenant - Restaurant": "bg-rose-600",
    "Tenant - Quick Service": "bg-rose-500",
    "Tenant - Café": "bg-rose-400",
    "Tenant - Bar": "bg-rose-500",
    "Tenant - Bakery": "bg-rose-400",
    "Tenant - Cinema": "bg-purple-600",
    "Tenant - Experiential": "bg-purple-500",
    "Tenant - Immersive Experience": "bg-purple-500",
    "Tenant - Gaming": "bg-purple-400",
    "Tenant - Family Entertainment": "bg-purple-400",
    "Tenant - Leisure": "bg-purple-500",
    "Tenant - Gym": "bg-orange-600",
    "Tenant - Wellness": "bg-orange-500",
    "Tenant - Yoga": "bg-orange-400",
    "Agent": "bg-blue-500",
  } as Record<string, string>,

  propertyStatus: ["BGP Targeting", "BGP Active", "Leasing Instruction", "Lease Advisory Instruction", "Sales Instruction", "Archive"],
  propertyEngagement: [
    "Investment",
    "London",
    "National",
    "Lease Advisory",
    "Tenant Rep",
    "Development",
    "Office / Corporate",
  ],
  propertyAssetClass: ["Office", "Leisure", "Retail", "Industrial", "Mixed Use"],
  propertyTenure: ["Freehold", "Leasehold"],

  // Canonical 10-code set — see shared/deal-status.ts. INV is system-set on Xero invoice sync.
  dealStatus: ["REP", "SPEC", "LIVE", "AVA", "NEG", "SOL", "EXC", "COM", "WIT", "INV"],
  dealType: [
    "Sale",
    "Purchase",
    "Lease Renewal",
    "Rent Review",
    "Tenant Rep",
    "Lease Acquisition",
    "Lease Disposal",
    "Regear",
    "New Letting",
    "Sub-Letting",
    "Assignment",
    "Investment Sale",
    "Investment Acquisition",
  ],
  dealTeam: ["Development", "London Leasing", "London F&B", "London Retail", "National Leasing", "Investment", "Tenant Rep", "Lease Advisory", "Office / Corporate", "Landsec"],
  dealAssetClass: ["Retail", "Leisure", "Office", "Hotel", "Resi", "Mixed Use", "Other"],
  dealFeeAgreement: ["YES", "NO"],
  dealAmlCheck: ["YES", "NO"],

  contactRole: [
    "Client",
    "Vendor",
    "Purchaser",
    "Agent",
    "Investor",
    "Developer",
    "Asset Manager",
    "Fund Manager",
    "MD",
    "Executive Director",
    "Investment Director",
    "Investment Associate",
    "Investment Executive - Retail",
    "Fund Management",
    "Head of Investment",
    "Head of Retail Parks",
    "Retail Asset Manager",
    "Business Space",
    "Leisure Fund",
    "London Offices",
  ],
  contactType: [
    "Retail",
    "Vendor",
    "Purchaser",
    "Tenant Rep",
    "Investor",
    "Developer",
    "Investment",
    "National",
    "Restaurant",
    "Retailer",
    "Lease",
    "Agent",
  ],
  agentSpecialty: [
    "Leasing",
    "Investment",
    "Tenant Rep",
    "Lease Advisory",
  ],
  agentSpecialtyColors: {
    "Leasing": "bg-blue-500",
    "Investment": "bg-indigo-500",
    "Tenant Rep": "bg-teal-500",
    "Lease Advisory": "bg-amber-500",
  } as Record<string, string>,
  contactBgpAllocation: [
    "Lease Advisory",
    "Investment",
    "London",
    "Tenant Rep",
    "National",
  ],
  bgpTeamColors: {
    "Lease Advisory": "bg-indigo-500",
    "Investment": "bg-sky-600",
    "London": "bg-zinc-700",
    "Tenant Rep": "bg-rose-500",
    "National": "bg-violet-500",
  } as Record<string, string>,

  reqLeasingStatus: ["Active", "Past", "Archived"],
  reqLeasingStatusColors: {
    "Active": "bg-emerald-500",
    "Past": "bg-rose-500",
    "Archived": "bg-zinc-400",
  } as Record<string, string>,
  reqLeasingUse: [
    "Retail",
    "Restaurant",
    "Leisure",
    "Other",
    "Wellness",
    "Gym",
    "A1 Food",
  ],
  reqLeasingUseColors: {
    "Retail": "bg-teal-500",
    "Restaurant": "bg-rose-500",
    "Leisure": "bg-purple-500",
    "Other": "bg-slate-500",
    "Wellness": "bg-cyan-500",
    "Gym": "bg-amber-500",
    "A1 Food": "bg-emerald-600",
  } as Record<string, string>,
  reqLeasingType: [
    "Shopping Centre",
    "High street",
    "Retail Park",
    "Leisure Park",
  ],
  reqLeasingTypeColors: {
    "Shopping Centre": "bg-indigo-500",
    "High street": "bg-orange-500",
    "Retail Park": "bg-sky-500",
    "Leisure Park": "bg-fuchsia-500",
  } as Record<string, string>,
  reqLeasingSize: [
    "Under 500 sq ft",
    "500 - 1,000 sq ft",
    "1,000 - 2,000 sq ft",
    "2,000 - 3,500 sq ft",
    "3,500 - 5,000 sq ft",
    "5,000 - 10,000 sq ft",
    "10,000 - 25,000 sq ft",
    "25,000 - 50,000 sq ft",
    "50,000 sq ft +",
  ],
  reqLeasingSizeColors: {
    "Under 500 sq ft": "bg-slate-500",
    "500 - 1,000 sq ft": "bg-lime-500",
    "1,000 - 2,000 sq ft": "bg-teal-500",
    "2,000 - 3,500 sq ft": "bg-blue-500",
    "3,500 - 5,000 sq ft": "bg-violet-500",
    "5,000 - 10,000 sq ft": "bg-amber-500",
    "10,000 - 25,000 sq ft": "bg-orange-500",
    "25,000 - 50,000 sq ft": "bg-rose-500",
    "50,000 sq ft +": "bg-red-700",
  } as Record<string, string>,
  reqLeasingLocations: ["Clapham", "East Anglia", "Ireland", "London", "Midlands", "N. Ireland", "National", "North East", "North West", "Scotland", "South East", "South West", "Wales"],
  reqLeasingLocationsColors: {
    "Clapham": "bg-pink-500",
    "East Anglia": "bg-amber-500",
    "Ireland": "bg-emerald-600",
    "London": "bg-blue-600",
    "Midlands": "bg-purple-500",
    "N. Ireland": "bg-teal-500",
    "National": "bg-emerald-500",
    "North East": "bg-sky-500",
    "North West": "bg-indigo-500",
    "Scotland": "bg-blue-800",
    "South East": "bg-orange-500",
    "South West": "bg-lime-600",
    "Wales": "bg-red-600",
  } as Record<string, string>,

  reqLeasingExtract: ["Yes", "No"],
  reqLeasingExtractColors: {
    "Yes": "bg-emerald-500",
    "No": "bg-rose-500",
  } as Record<string, string>,

  reqInvestmentUse: [
    "Retail",
    "Office",
    "Industrial / Logistics",
    "Residential / BTR",
    "Hotel",
    "Leisure",
    "Healthcare",
    "Student Accommodation",
    "Mixed Use",
    "Development",
    "Ground Rent",
    "Long Income",
    "Data Centre",
    "Life Sciences",
    "Self Storage",
    "Car Park",
    "Other",
  ],
  reqInvestmentUseColors: {
    "Retail": "bg-teal-500",
    "Office": "bg-blue-500",
    "Industrial / Logistics": "bg-amber-600",
    "Residential / BTR": "bg-rose-500",
    "Hotel": "bg-purple-500",
    "Leisure": "bg-fuchsia-500",
    "Healthcare": "bg-emerald-500",
    "Student Accommodation": "bg-cyan-500",
    "Mixed Use": "bg-indigo-500",
    "Development": "bg-orange-500",
    "Ground Rent": "bg-lime-600",
    "Long Income": "bg-sky-600",
    "Data Centre": "bg-slate-600",
    "Life Sciences": "bg-green-600",
    "Self Storage": "bg-yellow-600",
    "Car Park": "bg-stone-500",
    "Other": "bg-gray-500",
  } as Record<string, string>,
  reqInvestmentLocations: [
    "West End",
    "City of London",
    "Mayfair",
    "Knightsbridge",
    "Chelsea",
    "Kensington",
    "Victoria",
    "Fitzrovia",
    "Marylebone",
    "Soho",
    "Covent Garden",
    "South Bank",
    "Canary Wharf",
    "Greater London",
    "South East",
    "South West",
    "Midlands",
    "North West",
    "North East",
    "East Anglia",
    "Scotland",
    "Wales",
    "National",
    "UK Wide",
    "Europe",
    "International",
  ],
  reqInvestmentLocationsColors: {
    "West End": "bg-blue-600",
    "City of London": "bg-indigo-600",
    "Mayfair": "bg-purple-500",
    "Knightsbridge": "bg-fuchsia-500",
    "Chelsea": "bg-pink-500",
    "Kensington": "bg-rose-500",
    "Victoria": "bg-violet-500",
    "Fitzrovia": "bg-sky-500",
    "Marylebone": "bg-cyan-500",
    "Soho": "bg-amber-500",
    "Covent Garden": "bg-orange-500",
    "South Bank": "bg-teal-500",
    "Canary Wharf": "bg-blue-800",
    "Greater London": "bg-blue-400",
    "South East": "bg-emerald-500",
    "South West": "bg-lime-600",
    "Midlands": "bg-yellow-600",
    "North West": "bg-red-500",
    "North East": "bg-red-600",
    "East Anglia": "bg-green-500",
    "Scotland": "bg-blue-900",
    "Wales": "bg-red-700",
    "National": "bg-emerald-600",
    "UK Wide": "bg-slate-600",
    "Europe": "bg-indigo-500",
    "International": "bg-gray-500",
  } as Record<string, string>,
  reqInvestmentType: [
    "Core",
    "Core Plus",
    "Value Add",
    "Opportunistic",
    "Development",
    "Income Strip",
    "Sale & Leaseback",
    "Forward Funding",
    "Portfolio",
  ],
  reqInvestmentTypeColors: {
    "Core": "bg-blue-500",
    "Core Plus": "bg-sky-500",
    "Value Add": "bg-amber-500",
    "Opportunistic": "bg-orange-500",
    "Development": "bg-rose-500",
    "Income Strip": "bg-emerald-500",
    "Sale & Leaseback": "bg-purple-500",
    "Forward Funding": "bg-teal-500",
    "Portfolio": "bg-indigo-500",
  } as Record<string, string>,
  reqInvestmentSize: [
    "Under £5m",
    "£5m - £10m",
    "£10m - £25m",
    "£25m - £50m",
    "£50m - £100m",
    "£100m - £250m",
    "£250m+",
  ],
  reqInvestmentSizeColors: {
    "Under £5m": "bg-slate-500",
    "£5m - £10m": "bg-lime-500",
    "£10m - £25m": "bg-teal-500",
    "£25m - £50m": "bg-blue-500",
    "£50m - £100m": "bg-violet-500",
    "£100m - £250m": "bg-orange-500",
    "£250m+": "bg-red-600",
  } as Record<string, string>,

  leadStatus: ["New", "Qualified - Building", "Qualified - Contact", "Disqualified"],
  leadType: ["Building", "Contact"],
  leadSource: ["Manual", "AI News Feed", "Referral"],

  compDealType: ["Purchase", "Lease Acquisition", "Lease Disposal", "Sale"],
} as const;
