-- PLA Matter tracker — Lease Advisory platform foundation (May 2026)
--
-- The Matter is the unit of work for Tom and Pete's Professional Lease Advisory
-- practice: rent reviews, lease renewals, dilapidations, service charge,
-- general advisory. Every Matter is anchored to a canonical property
-- (crm_properties via the resolver) and a client (contact + company), and
-- automatically gets a SharePoint folder mirroring the BGP Lease Advisory
-- folder template Tom and Pete already use:
--
--   Lease Advisory/
--   └── <Property name>/
--       ├── Lease Documents/  (Current Lease, Licences, Supplements)
--       ├── Correspondence/
--       ├── Legal/
--       ├── Dilapidations/    (Schedule, Scott Schedule, Costings)
--       ├── Rent Review/      (Comparable Evidence, Representations, Valuation)
--       ├── Lease Renewal/    (Counter Notice)
--       └── Service Charge/
--
-- Comps and valuation workbooks (Net Effective, Devaluation, Comparables
-- Schedule) link in via pla_matter_comps + pla_matter_workbooks (added in
-- a follow-up migration once the valuation engine lands).

CREATE TABLE IF NOT EXISTS pla_matters (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Canonical property identity — populated by the Property Resolver.
  property_id varchar NOT NULL,

  -- What kind of matter is this
  matter_type text NOT NULL,           -- 'rent_review' | 'lease_renewal' | 'dilapidations' | 'service_charge' | 'general'

  -- Who's it for
  client_contact_id varchar,           -- → crm_contacts
  client_company_id varchar,           -- → crm_companies
  acting_for text,                     -- 'landlord' | 'tenant'

  -- Who's running it
  lead_user_id varchar NOT NULL,       -- → users (Tom, Pete, etc)
  team_user_ids text[],                -- supporting staff

  -- The lease itself (snapshot at matter creation; the live lease lives in
  -- crm_properties / lease_events but this captures the position we're
  -- arguing from)
  current_rent numeric,
  current_rent_review_date date,
  break_date date,
  expiry_date date,

  -- Active negotiation / valuation
  quoting_rent numeric,                -- our position
  counter_quoting_rent numeric,        -- the other side's position
  agreed_rent numeric,                 -- once settled

  -- Notice tracking (rent review / 1954 Act renewal)
  notice_served_at timestamp,
  notice_served_by text,               -- 'us' | 'them'
  counter_notice_deadline timestamp,
  counter_notice_served_at timestamp,

  -- Workflow
  status text NOT NULL DEFAULT 'open', -- 'open' | 'in_negotiation' | 'agreed' | 'settled' | 'closed' | 'on_hold'
  opened_at timestamp DEFAULT now(),
  settled_at timestamp,
  closed_at timestamp,

  -- SharePoint folder — auto-created on Matter creation using Tom and Pete's
  -- canonical Lease Advisory folder template
  sharepoint_folder_url text,
  folder_template_applied boolean DEFAULT false,

  -- Free-form
  notes text,

  -- Tags for filter/search
  tags text[],

  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

-- Indexes for the hot lookup paths
CREATE INDEX IF NOT EXISTS pla_matters_property_idx ON pla_matters (property_id);
CREATE INDEX IF NOT EXISTS pla_matters_lead_idx     ON pla_matters (lead_user_id);
CREATE INDEX IF NOT EXISTS pla_matters_status_idx   ON pla_matters (status) WHERE status NOT IN ('closed','settled');
CREATE INDEX IF NOT EXISTS pla_matters_review_idx   ON pla_matters (current_rent_review_date) WHERE current_rent_review_date IS NOT NULL;

-- Linked comparables — many comps may inform one matter
CREATE TABLE IF NOT EXISTS pla_matter_comps (
  matter_id varchar NOT NULL,
  comp_id varchar NOT NULL,
  weight real DEFAULT 1.0,             -- how much this comp influences the valuation (0–1)
  notes text,
  added_by varchar,
  added_at timestamp DEFAULT now(),
  PRIMARY KEY (matter_id, comp_id)
);

CREATE INDEX IF NOT EXISTS pla_matter_comps_comp_idx ON pla_matter_comps (comp_id);

-- Workbook artefacts — net effective, devaluation, comparables schedule —
-- generated by the valuation engine and stored in SharePoint. Keeping
-- pointers so we can show them on the Matter page and re-render them.
CREATE TABLE IF NOT EXISTS pla_matter_workbooks (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  matter_id varchar NOT NULL,
  kind text NOT NULL,                  -- 'net_effective' | 'devaluation' | 'comparables_schedule' | 'representations'
  sharepoint_url text,
  generated_at timestamp DEFAULT now(),
  generated_by varchar,
  inputs_snapshot jsonb,               -- the exact input figures used — for audit
  output_summary jsonb                 -- key results: ITZA rate, headline, net effective psf
);

CREATE INDEX IF NOT EXISTS pla_matter_workbooks_matter_idx ON pla_matter_workbooks (matter_id);

-- Key dates — surface on dashboards, drive reminders. Pulled out so a single
-- matter can have many dated events (notice served, counter deadline, hearing,
-- expert determination booking, etc.) without bloating the main row.
CREATE TABLE IF NOT EXISTS pla_matter_events (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  matter_id varchar NOT NULL,
  event_kind text NOT NULL,            -- 'notice_served' | 'counter_notice_deadline' | 'hearing' | 'inspection' | 'meeting' | 'court' | 'expert_determination' | 'agreed' | 'note'
  event_date timestamp NOT NULL,
  description text,
  done boolean DEFAULT false,
  done_at timestamp,
  created_by varchar,
  created_at timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pla_matter_events_matter_idx ON pla_matter_events (matter_id);
CREATE INDEX IF NOT EXISTS pla_matter_events_upcoming_idx ON pla_matter_events (event_date) WHERE done = false;
