import { go, report, tap, browser, page, BASE, ctx, user, shot } from './r552-client-mobile-journey.mjs';
const UID = '99ee6031-384a-4799-94a4-8aba5dda89b1';
await go('/available', 'tracker');
await page.locator('input[placeholder*="Search" i]').first().fill('U124'); await page.waitForTimeout(1500);
await tap(`[data-testid="unit-edit-${UID}"]`, 'edit-open');
const trig = page.locator('[role="dialog"] button[role="combobox"]').nth(5);
await trig.click(); await page.waitForTimeout(700);
const opts = await page.evaluate(() => [...document.querySelectorAll('[role="option"]')].map(o => o.textContent.trim()));
console.log('STATUS OPTIONS: ' + JSON.stringify(opts));
await shot('status-options');
const target = opts.find(o => /negotiat/i.test(o)) || opts[1];
await page.locator('[role="option"]').filter({ hasText: target }).first().click();
await page.waitForTimeout(500);
console.log('picked', target, '->', await trig.innerText());
await shot('status-picked');
const save = page.locator('[role="dialog"] button', { hasText: /^Save$/ }).last();
await save.click();
await page.waitForTimeout(3000);
await shot('after-save');
const i = await report('tracker-after-save');
console.log('--- COUNTERS ---\n' + i.txt.slice(0, 700));
await browser.close();
