import { chromium } from '../node_modules/playwright/index.mjs';
import { existsSync } from 'fs';
const BASE='http://localhost:5000';
const QA = existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : null;
const browser = await chromium.launch(QA?{executablePath:QA,args:['--no-sandbox']}:{args:['--no-sandbox']});
const ctx = await browser.newContext({ viewport:{width:1440,height:900}, locale:'en-GB' });
const r = await ctx.request.post(`${BASE}/api/auth/login`,{data:{username:'victoria@brucegillinghampollard.com',password:'B@nd0077!'}});
const user = await r.json();
const api = async (m,p,d)=>{const res=await ctx.request.fetch(`${BASE}${p}`,{method:m,headers:{Authorization:`Bearer ${user.token}`,'Content-Type':'application/json'},data:d});let b=null;try{b=await res.json()}catch{};return{status:res.status(),body:b}};
const page = await ctx.newPage();
const t0=Date.now();
page.on('request', rq => { if (rq.method()!=='GET' && /\/api\//.test(rq.url())) console.log(`   +${Date.now()-t0} REQ ${rq.method()} ${rq.url().replace(BASE,'')}`); });
page.on('response', rs => { if (rs.request().method()!=='GET' && /\/api\//.test(rs.url())) console.log(`   +${Date.now()-t0} RES ${rs.request().method()} ${rs.url().replace(BASE,'')} ${rs.status()}`); });
page.on('requestfailed', rq => { if (/\/api\//.test(rq.url())) console.log(`   +${Date.now()-t0} FAIL ${rq.method()} ${rq.url().replace(BASE,'')} ${rq.failure()?.errorText}`); });
page.on('pageerror', e => console.log('   PAGEERROR', e.message));
await page.goto(BASE).catch(()=>{});
await page.evaluate(([t,u])=>{localStorage.setItem('bgp_auth_token',t);localStorage.setItem('authToken',t);localStorage.setItem('user',JSON.stringify(u));},[user.token,user]);
await page.goto(BASE+'/lease-events',{waitUntil:'domcontentloaded'}).catch(()=>{});
await page.waitForLoadState('networkidle').catch(()=>{});
await page.waitForTimeout(6000);
const tag='diag';
const made = await api('POST','/api/lease-events',{tenant:'QA-PROBE race '+tag,eventType:'Break Option',status:'Monitoring',sourceEvidence:'Manual',eventDate:new Date(Date.now()+120*864e5).toISOString().slice(0,10)});
await page.goto(BASE+'/lease-events',{waitUntil:'domcontentloaded'}).catch(()=>{});
await page.waitForLoadState('networkidle').catch(()=>{});
const row = () => page.locator('table tbody tr', { hasText: 'QA-PROBE race '+tag }).first();
await row().waitFor({ timeout: 30000 });
const cacheStatus = async (label) => {
  const v = await page.evaluate(() => {
    try {
      const raw = JSON.parse(localStorage.getItem('bgp-query-cache')||'null');
      if (!raw) return 'NO-CACHE';
      const q = (raw.clientState?.queries||[]).find(x => JSON.stringify(x.queryKey)==='["/api/lease-events"]');
      if (!q) return 'no lease-events query in cache';
      const row = (q.state.data||[]).find(e => (e.tenant||'').includes('QA-PROBE race'));
      return `cacheTs=${raw.timestamp} dataUpdatedAt=${q.state.dataUpdatedAt} status=${row?row.status:'(row absent)'} ageOfSnapshot=${Date.now()-raw.timestamp}ms`;
    } catch (e) { return 'ERR '+e.message; }
  });
  console.log(`   [${label}] ${v}`);
};
await cacheStatus('before click');
console.log('--- clicking Contacted ---');
await row().locator('button[role="combobox"]').nth(0).click();
await page.waitForTimeout(600);
await page.locator('[role="option"]', { hasText: /^Contacted$/ }).first().click();
await page.waitForTimeout(300);
console.log('   row now shows:', (await row().locator('button[role="combobox"]').nth(0).innerText()).trim());
console.log('   db now:', (await api('GET','/api/lease-events')).body.find(x=>x.tenant==='QA-PROBE race '+tag)?.status);
await cacheStatus('300ms after click');
await page.waitForTimeout(1500);
await cacheStatus('1800ms after click');
console.log('--- reload ---');
await page.reload({waitUntil:'domcontentloaded'}).catch(()=>{});
await page.waitForLoadState('networkidle').catch(()=>{});
await row().waitFor({ timeout: 30000 });
await page.waitForTimeout(1500);
console.log('   after reload row shows:', (await row().locator('button[role="combobox"]').nth(0).innerText()).trim());
console.log('   db after reload:', (await api('GET','/api/lease-events')).body.find(x=>x.tenant==='QA-PROBE race '+tag)?.status);
await page.waitForTimeout(4000);
console.log('   +4s later row shows:', (await row().locator('button[role="combobox"]').nth(0).innerText()).trim());
await api('DELETE','/api/lease-events/'+made.body.id);
await browser.close();
