import { go, page, browser, ctx, BASE, user } from './r560-client-mobile-journey.mjs';
const H = { Authorization: `Bearer ${user.token}` };
const ins = await ctx.request.get(`${BASE}/api/microsoft/calendar/insights`, { headers: H });
const mj = await ins.json();
console.log('MARK insights ->', ins.status());
for (const i of mj.insights) console.log(`   ${i.title}: ${i.detail}`);
console.log('  busiestAgent present for client?', mj.insights.some(i=>i.type==='busiestAgent'));
console.log('  any bgp email leaked?', /brucegillinghampollard/i.test(JSON.stringify(mj)));
await go('/calendar', 'calendar-client-after');
await page.waitForTimeout(4000);
const t = await page.evaluate(()=>({txt:document.body.innerText.replace(/\n{2,}/g,'\n'),ov:document.documentElement.scrollWidth-window.innerWidth}));
console.log(`\n== CLIENT CALENDAR overflow ${t.ov}\n${t.txt.slice(0,1400)}`);
await page.screenshot({ path: 'qa/smoke-shots/r560-fix-calendar-client.png', fullPage: true });
const vr = await ctx.request.post(`${BASE}/api/auth/login`, { data: { username: 'victoria@brucegillinghampollard.com', password: 'B@nd0077!' } });
const v = await vr.json();
const vi = await (await ctx.request.get(`${BASE}/api/microsoft/calendar/insights`, { headers: { Authorization: `Bearer ${v.token}` } })).json();
console.log('\nVICTORIA insights ->');
for (const i of vi.insights) console.log(`   ${i.title}: ${i.detail}`);
console.log('  staff keeps busiestAgent?', vi.insights.some(i=>i.type==='busiestAgent'));
await browser.close();
