import { chromium } from '/home/user/bgp-wip-app/node_modules/playwright/index.mjs';
const BASE='http://127.0.0.1:5000';
const browser = await chromium.launch({executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox']});
const ctx = await browser.newContext({viewport:{width:1440,height:1000}});
const page = await ctx.newPage();
page.on('console',m=>{ if(m.type()==='error') console.log('  [console]', m.text().slice(0,180)); });
page.on('response',r=>{ if(r.status()>=400 && r.url().includes('/api/')) console.log('  [http]', r.status(), r.request().method(), r.url().replace(BASE,'')); });
const t=await (await ctx.request.post(`${BASE}/api/auth/login`,{data:{username:'mark.warne@landsec.com',password:'B@nd0077!'}})).json();
await page.goto(BASE+'/login',{waitUntil:'domcontentloaded'}).catch(()=>{});
await page.evaluate(x=>localStorage.setItem('authToken',x), t.token);
await page.goto(BASE+'/tenancy-schedule/cccccccc-0000-0000-0000-000000000001',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(9000);
const btn=page.locator('button:has-text("Message your team")').first();
console.log('Message your team button count:', await page.locator('button:has-text("Message your team")').count());
await btn.click();
await page.waitForTimeout(3000);
await page.screenshot({path:'qa/smoke-shots/r566-s11-msg.png'});
console.log('URL:', page.url());
const ta = await page.evaluate(()=>[...document.querySelectorAll('textarea,input[type=text]')].map(i=>({tid:i.getAttribute('data-testid')||'',ph:i.placeholder||''})));
console.log('FIELDS:', JSON.stringify(ta));
const body = await page.evaluate(()=>document.body.innerText.replace(/\s+/g,' ').slice(0,600));
console.log('BODY:', body);
await browser.close();
