import { chromium } from 'playwright';
import { existsSync } from 'fs';
const BASE='http://127.0.0.1:5000', SHOT='qa/smoke-shots';
const PID='cccccccc-0000-0000-0000-000000000001';
const browser = await chromium.launch({ executablePath: existsSync('/opt/pw-browsers/chromium')?'/opt/pw-browsers/chromium':undefined, args:['--no-sandbox'] });
const raw=browser.newContext.bind(browser); browser.newContext=async o=>{const c=await raw(o);await c.route(/^https?:\/\/(?!localhost|127\.0\.0\.1)/,r=>r.abort());return c;};
const ctx=await browser.newContext({viewport:{width:390,height:780},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true,locale:'en-GB',timezoneId:'Europe/London'});
const user=await (await ctx.request.post(BASE+'/api/auth/login',{data:{username:'mark.warne@landsec.com',password:'B@nd0077!'}})).json();
const page=await ctx.newPage();
const net=[]; page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)net.push(`${r.status()} ${r.request().method()} ${r.url().replace(BASE,'')}`);});
page.on('pageerror',e=>console.log('  [PAGEERROR]',e.message));
await page.goto(BASE);
await page.evaluate(([t,u])=>{localStorage.setItem('authToken',t);localStorage.setItem('user',JSON.stringify(u));},[user.token,user]);
await page.goto(`${BASE}/properties/${PID}`,{waitUntil:'domcontentloaded'});
await page.waitForTimeout(9000);
await page.screenshot({path:`${SHOT}/r576-phone-property.png`,fullPage:true});
console.log((await page.evaluate(()=>document.body.innerText)).replace(/\n{2,}/g,'\n').slice(0,3500));
console.log('\nNET>=400: '+[...new Set(net)].join(' ; '));
await browser.close();
